### ISSUE TITLE
Bearer-only

### ISSUE THREAD

**Issue by ErshovYS** [gitfish/express-gateway-keycloak#1]
Hi @gitfish ! I have problem with bearer authorization.
Plugin returns "Access Denied" in all times when `bearer-only: true` in keycloakConfig.
It seems that the config:
```
plugins:
  express-gateway-keycloak:
    package: express-gateway-keycloak
    keycloakConfig:
        realm: sample
        bearer-only: true
#        public-client: true
        auth-server-url: "http://localhost:8089/auth"
        ssl-required: external
        resource: keycloak-express
        verify-token-audience: true
        use-resource-role-mapping: true
        confidential-port: 0
```
I try protect by role, realm:role and group - "Access Denied" at all.
And when `public-client: true` Plugin works fine with redirecting.
